[build]
  command = "npm run build"
  publish = "public"
[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    record = false
    group = 'deployed'
  [plugins.inputs.postBuild]
    # run E2E tests against locally built site
    # before deploying it
    enable = true
    record = false
    group = 'built'