local_backend: true
backend:
  name: 'github'
  repo: 'MarinaNitze/progress-dashboard'
  branch: 'main'
publish_mode: 'editorial_workflow'

media_folder: 'src/images'

collections:
  - label: "Pages"
    name: "pages"
    files:
    - name: "About"
      label: "About"
      file: "src/about/index.md"
      fields:
        - {label: "Page Title", name: "title", widget: "string"}
        - {label: "Layout", name: "layout", widget: "hidden", default: "content" }
        - {label: "Page Header", name: "header", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
